name: Sync Upstream Repository

# 设定触发机制：
# 1. schedule: 每小时运行一次 (近似实时)
# 2. workflow_dispatch: 可以在 GitHub 页面手动点击运行
on:
  schedule:
    - cron: '0 * * * *' # Cron 表达式：表示每小时的第 0 分钟运行一次
  workflow_dispatch:

jobs:
  sync_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # 0 表示获取全部历史记录
          fetch-depth: 0 
          
      - name: Auto Sync with Upstream
        # 使用一个专门用于同步 Fork 的 Actions
        uses: tgymnich/fork-sync@v2
        with:
          # 【重要！】替换为您要同步的原始仓库地址
          # 格式：原作者用户名/原仓库名称
          upstream_repository: 'https://github.com/cmliu/epeius'
          
          # 要同步的原仓库分支
          upstream_branch: 'main'
          
          # 您的复制仓库要更新的分支
          target_branch: 'main'
          
          # 使用 GitHub 自动提供的权限 Token
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          # 自动合并，无需手动创建 Pull Request
          auto_merge: true
